import { useCallback, useEffect, useRef, useState } from "react";
import { reviewApi } from "../services/api";
import { launchPlatform } from "../services/app-launcher";
import { copyText } from "../utils/clipboard";
import { parseEntryParams } from "../utils/entry-params";
import { track } from "../services/analytics-service";
import { useReviewFlowStore } from "../stores/review-flow-store";

export function useReviewFlow() {
  const state = useReviewFlowStore(); const initialized = useRef(false); const [copied, setCopied] = useState(false); const [launchHint, setLaunchHint] = useState("");
  const context = { merchantId: state.config?.merchant.id || "", storeId: state.config?.store.id, sessionId: state.sessionId || undefined };
  const initialize = useCallback(async () => { const s = useReviewFlowStore.getState(); s.setLoading(true); s.setLoadError(""); try { const entry = parseEntryParams(location.search); const config = await reviewApi.config(entry.storeId); if (entry.merchantId && entry.merchantId !== config.merchant.id) throw new Error("二维码商户信息与门店不匹配"); const session = await reviewApi.createSession({ merchantId: config.merchant.id, storeId: config.store.id }); s.setConfig(config); s.setSessionId(session.id); track({ merchantId: config.merchant.id, storeId: config.store.id, sessionId: session.id }, "page_view", { scene: entry.scene }); } catch (e) { s.setLoadError(e instanceof Error ? e.message : "加载失败，请重试"); } finally { s.setLoading(false); } }, []);
  useEffect(() => { if (!initialized.current) { initialized.current = true; void initialize(); } }, [initialize]);
  const go = (screen: typeof state.screen) => { state.setActionError(""); state.setScreen(screen); track(context, "step_view", { screen }); };
  const generate = async () => { if (!state.config || !state.sessionId || !state.dishIds.length) return; state.setActionError(""); state.setLoading(true); go("generating"); const started = Date.now(); try { await reviewApi.updateSession(state.sessionId, { dishIds: state.dishIds, tagIds: state.tagIds, message: state.message }); const result = await reviewApi.generateReviews({ merchantId: state.config.merchant.id, storeId: state.config.store.id, sessionId: state.sessionId, input: { dishes: state.dishIds, tags: state.tagIds, message: state.message } }); await new Promise((r) => setTimeout(r, Math.max(0, 900 - (Date.now() - started)))); state.setReviews(result.reviews); go("reviews"); track(context, "review_generated", { count: result.reviews.length }); } catch (e) { state.setActionError(e instanceof Error ? e.message : "生成失败，请重试"); go("message"); } finally { state.setLoading(false); } };
  const persistSelection = async () => { const review = state.reviews.find((r) => r.id === state.selectedReviewId); if (!review) return; state.setLoading(true); try { await reviewApi.selectReview(review.id, review.content); state.selectReview(review.id, review.content); go("platform"); track(context, "review_selected", { reviewId: review.id }); } catch (e) { state.setActionError(e instanceof Error ? e.message : "保存失败，请重试"); } finally { state.setLoading(false); } };
  const copy = async () => { try { await copyText(state.selectedContent); setCopied(true); setLaunchHint(""); } catch (e) { setLaunchHint(e instanceof Error ? e.message : "复制失败"); } };
  const launch = async (platformId: string) => { if (!state.config) return; state.setLoading(true); state.selectPlatform(platformId); setLaunchHint(""); try { const prepared = await reviewApi.preparePublish(state.sessionId, platformId); const result = await launchPlatform({ platform: platformId, scheme: prepared.scheme, copyText: prepared.copyText, storeName: state.config.store.name }); setCopied(true); setLaunchHint(result.opened ? "" : result.hint); track(context, "platform_clicked", { platformId }); } catch (e) { setLaunchHint(e instanceof Error ? e.message : "打开应用失败"); } finally { state.setLoading(false); } };
  const complete = async () => { state.setLoading(true); try { await reviewApi.completePublish(state.sessionId); go("completion"); track(context, "publish_confirmed", { platformId: state.selectedPlatformId }); } catch (e) { setLaunchHint(e instanceof Error ? e.message : "请先选择发布平台"); } finally { state.setLoading(false); } };
  const claim = async () => { state.setLoading(true); state.setActionError(""); try { state.setReward(await reviewApi.claimReward(state.sessionId)); track(context, "reward_claimed"); } catch (e) { state.setActionError(e instanceof Error ? e.message : "领取失败，请重试"); } finally { state.setLoading(false); } };
  return { ...state, initialize, go, generate, persistSelection, copy, launch, complete, claim, copied, launchHint, closeReward: () => state.setReward(undefined) };
}
